openapi: 3.2.0
info:
  version: 2.0.0
  title: Webflow Data Items API
  description: Webflow's Data API v2
  termsOfService: https://webflow.com/legal/terms
  contact:
    name: Webflow Developer Relations
    email: developers@webflow.com
    url: https://developers.webflow.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: https://api.webflow.com/v2
  description: Webflow API v2
  x-fern-server-name: Data API
security:
- OAuth2: []
- ApiKey: []
tags:
- name: Items
  description: Items are the individual e-commerce items in your Webflow site.
paths: {}
webhooks:
  collection_item_created:
    post:
      operationId: collection_item_created
      summary: Collection Item Created
      description: Information about a new collection item
      tags:
      - Items
      requestBody:
        description: The information about the collection item that was created
        content:
          application/json:
            schema:
              description: The Webhook payload for when a Collection Item is created
              type: object
              required:
              - triggerType
              - payload
              properties:
                triggerType:
                  description: The type of event that triggered the request
                  type: string
                  enum:
                  - collection_item_created
                payload:
                  type: object
                  title: Collection Item without Locales
                  required:
                  - id
                  - workspaceId
                  - siteId
                  - collectionId
                  - fieldData
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: Unique identifier for the Item
                    workspaceId:
                      type: string
                      format: uuid
                      description: Unique identifier of the workspace
                    siteId:
                      type: string
                      format: uuid
                      description: Unique identifier of the site
                    collectionId:
                      type: string
                      format: uuid
                      description: Unique identifier of the collection
                    cmsLocaleId:
                      type: string
                      format: uuid
                      description: Unique identifier of the CMS locale for this item
                      nullable: true
                    lastPublished:
                      type: string
                      format: date-time
                      nullable: true
                    lastUpdated:
                      type: string
                      format: date-time
                    createdOn:
                      type: string
                      format: date-time
                    isArchived:
                      type: boolean
                    isDraft:
                      type: boolean
                    fieldData:
                      type: object
                      required:
                      - name
                      - slug
                      properties:
                        name:
                          type: string
                        slug:
                          type: string
                      additionalProperties: true
                  example:
                    id: 580e64008c9a982ac9b8b754
                    workspaceId: 625860a7a6c16d624927122f
                    siteId: 65427cf400e02b306eaa049c
                    collectionId: 664243617fcc8b464b23c4ee
                    cmsLocaleId: 681442a144bb80bd00480fda
                    lastPublished: null
                    lastUpdated: '2023-03-17T18:47:35.560Z'
                    createdOn: '2023-03-17T18:47:35.560Z'
                    isArchived: false
                    isDraft: false
                    fieldData:
                      name: Pan-Galactic Gargle Blaster
                      slug: pan-galactic-gargle-blaster
              example:
                triggerType: collection_item_created
                payload:
                  id: 580e64008c9a982ac9b8b754
                  workspaceId: 625860a7a6c16d624927122f
                  siteId: 65427cf400e02b306eaa049c
                  collectionId: 664243617fcc8b464b23c4ee
                  lastPublished: '2023-03-17T18:47:35.560Z'
                  lastUpdated: '2023-03-17T18:47:35.560Z'
                  createdOn: '2023-03-17T18:47:35.560Z'
                  isArchived: false
                  isDraft: false
                  fieldData:
                    name: Pan-Galactic Gargle Blaster
                    slug: pan-galactic-gargle-blaster
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  collection_item_changed:
    post:
      operationId: collection_item_changed
      summary: Collection Item Updated
      description: Information about an updated collection item
      tags:
      - Items
      requestBody:
        description: The information about the collection item that was changed
        content:
          application/json:
            schema:
              description: The Webhook payload for when a Collection Item is changed
              type: object
              required:
              - triggerType
              - payload
              properties:
                triggerType:
                  description: The type of event that triggered the request
                  type: string
                  enum:
                  - collection_item_changed
                payload:
                  type: object
                  title: Collection Item without Locales
                  required:
                  - id
                  - workspaceId
                  - siteId
                  - collectionId
                  - fieldData
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: Unique identifier for the Item
                    workspaceId:
                      type: string
                      format: uuid
                      description: Unique identifier of the workspace
                    siteId:
                      type: string
                      format: uuid
                      description: Unique identifier of the site
                    collectionId:
                      type: string
                      format: uuid
                      description: Unique identifier of the collection
                    cmsLocaleId:
                      type: string
                      format: uuid
                      description: Unique identifier of the CMS locale for this item
                      nullable: true
                    lastPublished:
                      type: string
                      format: date-time
                      nullable: true
                    lastUpdated:
                      type: string
                      format: date-time
                    createdOn:
                      type: string
                      format: date-time
                    isArchived:
                      type: boolean
                    isDraft:
                      type: boolean
                    fieldData:
                      type: object
                      required:
                      - name
                      - slug
                      properties:
                        name:
                          type: string
                        slug:
                          type: string
                      additionalProperties: true
                  example:
                    id: 580e64008c9a982ac9b8b754
                    workspaceId: 625860a7a6c16d624927122f
                    siteId: 65427cf400e02b306eaa049c
                    collectionId: 664243617fcc8b464b23c4ee
                    cmsLocaleId: 681442a144bb80bd00480fda
                    lastPublished: null
                    lastUpdated: '2023-03-17T18:47:35.560Z'
                    createdOn: '2023-03-17T18:47:35.560Z'
                    isArchived: false
                    isDraft: false
                    fieldData:
                      name: Pan-Galactic Gargle Blaster
                      slug: pan-galactic-gargle-blaster
              example:
                triggerType: collection_item_changed
                payload:
                  triggerType: collection_item_created
                  payload:
                    id: 580e64008c9a982ac9b8b754
                    workspaceId: 625860a7a6c16d624927122f
                    siteId: 65427cf400e02b306eaa049c
                    collectionId: 664243617fcc8b464b23c4ee
                    lastPublished: '2023-03-17T18:47:35.560Z'
                    lastUpdated: '2023-03-17T18:47:35.560Z'
                    createdOn: '2023-03-17T18:47:35.560Z'
                    isArchived: false
                    isDraft: false
                    fieldData:
                      name: Pan-Galactic Gargle Blaster
                      slug: pan-galactic-gargle-blaster
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  collection_item_deleted:
    post:
      operationId: collection_item_deleted
      summary: Collection Item Deleted
      description: Information about a deleted collection item
      tags:
      - Items
      requestBody:
        description: The results from deleting the collection item
        content:
          application/json:
            schema:
              properties:
                triggerType:
                  description: The type of event that triggered the request
                  type: string
                  example: collection_item_deleted
                payload:
                  description: The payload of data sent from Webflow
                  type: object
                  properties:
                    id:
                      type: string
                      format: objectid
                      description: The ID of the collection item that was deleted
                      example: 6321ca84df3949bfc6752327
                    siteId:
                      type: string
                      format: objectid
                      description: The ID of the site
                      example: 65427cf400e02b306eaa049c
                    workspaceId:
                      type: string
                      format: objectid
                      description: The ID of the workspace
                      example: 625860a7a6c16d624927122f
                    collectionId:
                      type: string
                      format: objectid
                      description: The ID of the collection
                      example: 664243617fcc8b464b23c4ee
                    cmsLocaleId:
                      type: string
                      format: uuid
                      description: Unique identifier of the CMS locale for this item
                      example: 681442a144bb80bd00480fda
                    lastPublished:
                      type: string
                      format: date-time
                      nullable: true
                    lastUpdated:
                      type: string
                      format: date-time
                    createdOn:
                      type: string
                      format: date-time
                    isArchived:
                      type: boolean
                    isDraft:
                      type: boolean
                    fieldData:
                      type: object
                      required:
                      - name
                      - slug
                      properties:
                        name:
                          type: string
                        slug:
                          type: string
                      additionalProperties: true
              example:
                triggerType: collection_item_deleted
                payload:
                  id: 66424365e972c886137a1cf1
                  siteId: 65427cf400e02b306eaa049c
                  workspaceId: 625860a7a6c16d624927122f
                  collectionId: 664243617fcc8b464b23c4ee
                  cmsLocaleId: 681442a144bb80bd00480fda
                  lastPublished: null
                  lastUpdated: '2025-05-28T04:44:33.216Z'
                  createdOn: '2025-05-28T04:27:12.667Z'
                  isArchived: false
                  isDraft: false
                  fieldData:
                    name: Earth
                    slug: earth
                    description: Mostly harmless
                    color: '#0000FF'
                    type: planet
                    galaxy: Milky Way
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  collection_item_published:
    post:
      operationId: collection_item_published
      summary: Collection Item Published
      description: Information about a collection item that was published
      tags:
      - Items
      requestBody:
        description: The results from publishing the collection item
        content:
          application/json:
            schema:
              properties:
                triggerType:
                  description: The type of event that triggered the request
                  type: string
                  example: collection_item_published
                payload:
                  description: The payload of data sent from Webflow
                  type: object
                  properties:
                    id:
                      type: string
                      format: objectid
                      description: The ID of the collection item that was unpublished
                      example: 6321ca84df3949bfc6752327
                    siteId:
                      type: string
                      format: objectid
                      description: The ID of the site
                      example: 65427cf400e02b306eaa049c
                    workspaceId:
                      type: string
                      format: objectid
                      description: The ID of the workspace
                      example: 625860a7a6c16d624927122f
                    collectionId:
                      type: string
                      format: objectid
                      description: The ID of the collection
                      example: 664243617fcc8b464b23c4ee
                    cmsLocaleId:
                      type: string
                      format: uuid
                      description: Unique identifier of the CMS locale for this item
                      example: 681442a144bb80bd00480fda
                      nullable: true
                    lastPublished:
                      type: string
                      format: date-time
                      nullable: true
                    lastUpdated:
                      type: string
                      format: date-time
                    createdOn:
                      type: string
                      format: date-time
                    isArchived:
                      type: boolean
                    isDraft:
                      type: boolean
                    fieldData:
                      type: object
                      required:
                      - name
                      - slug
                      properties:
                        name:
                          type: string
                        slug:
                          type: string
                      additionalProperties: true
              example:
                triggerType: collection_item_published
                payload:
                  id: 66424365e972c886137a1cf1
                  siteId: 65427cf400e02b306eaa049c
                  workspaceId: 625860a7a6c16d624927122f
                  collectionId: 664243617fcc8b464b23c4ee
                  cmsLocaleId: 681442a144bb80bd00480fda
                  lastPublished: null
                  lastUpdated: '2025-05-28T04:44:33.216Z'
                  createdOn: '2025-05-28T04:27:12.667Z'
                  isArchived: false
                  isDraft: false
                  fieldData:
                    _locale: 681442a144bb80bd00480fda
                    _noSearch: false
                    name: Anna Gunn
                    slug: anna-gunn
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
  collection_item_unpublished:
    post:
      operationId: collection_item_unpublished
      summary: Collection Item Unpublished
      description: Information about a collection item that was removed from the live site
      tags:
      - Items
      requestBody:
        description: The results from unpublishing the collection item
        content:
          application/json:
            schema:
              properties:
                triggerType:
                  description: The type of event that triggered the request
                  type: string
                  example: collection_item_unpublished
                payload:
                  description: The payload of data sent from Webflow
                  type: object
                  properties:
                    id:
                      type: string
                      format: objectid
                      description: The ID of the collection item that was unpublished
                      example: 6321ca84df3949bfc6752327
                    siteId:
                      type: string
                      format: objectid
                      description: The ID of the site
                      example: 65427cf400e02b306eaa049c
                    workspaceId:
                      type: string
                      format: objectid
                      description: The ID of the workspace
                      example: 625860a7a6c16d624927122f
                    collectionId:
                      type: string
                      format: objectid
                      description: The ID of the collection
                      example: 664243617fcc8b464b23c4ee
                    cmsLocaleId:
                      type: string
                      format: uuid
                      description: Unique identifier of the CMS locale for this item
                      example: 681442a144bb80bd00480fda
                      nullable: true
                    lastPublished:
                      type: string
                      format: date-time
                      nullable: true
                    lastUpdated:
                      type: string
                      format: date-time
                    createdOn:
                      type: string
                      format: date-time
                    isArchived:
                      type: boolean
                    isDraft:
                      type: boolean
                    fieldData:
                      type: object
                      required:
                      - name
                      - slug
                      properties:
                        name:
                          type: string
                        slug:
                          type: string
                      additionalProperties: true
              example:
                triggerType: collection_item_unpublished
                payload:
                  id: 66424365e972c886137a1cf1
                  siteId: 65427cf400e02b306eaa049c
                  workspaceId: 625860a7a6c16d624927122f
                  collectionId: 664243617fcc8b464b23c4ee
                  cmsLocaleId: 681442a144bb80bd00480fda
                  lastPublished: null
                  lastUpdated: '2025-05-28T04:44:33.216Z'
                  createdOn: '2025-05-28T04:27:12.667Z'
                  isArchived: false
                  isDraft: false
                  fieldData:
                    _locale: 681442a144bb80bd00480fda
                    _noSearch: false
                    name: Anna Gunn
                    slug: anna-gunn
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            authorized_user:read: read details about the authorized user
            assets:read: read assets on the site
            assets:write: write assets on a site
            cms:read: read collections and items for a site
            cms:write: write to collections and items for a site
            comments:read: read comments on the site
            comments:write: write comments on the site
            custom_code:read: read custom code on the site
            custom_code:write: modify custom code on the site
            ecommerce:read: read ecommerce data
            ecommerce:write: edit ecommerce data
            forms:read: read form data
            forms:write: write form data
            pages:read: read pages on the site
            pages:write: write to pages on the site
            components:read: read component data
            components:write: write component data
            sites:read: read sites on the site
            sites:write: modify pages on the site
            users:read: read users on the site
            site_activity:read: read site activity logs
            users:write: modify users on the site
            workspace:read: read workspace resource data
            workspace:write: write workspace resource data
            site_config:read: read site configuration data
            site_config:write: write site configuration data
          authorizationUrl: https://webflow.com/oauth/authorize
          tokenUrl: https://api.webflow.com/oauth/token
    ApiKey:
      type: http
      scheme: bearer
      x-fern-token-variable-name: access_token
